# TODO: 从 Fabric Develop 页面填入 26.1 推荐版本
# https://docs.fabricmc.net/develop/porting/next

deps.fabric_loader=TODO_REPLACE_WITH_26_1_RECOMMENDED_LOADER
deps.fabric_api=TODO_REPLACE_WITH_26_1_RECOMMENDED_FABRIC_API

# Minecraft dependency for fabric.mod.json
mod.mc_dep=26.1

# Release title for Modrinth and Curseforge
mod.mc_title=26.1

# Space-separated compatible versions for publishing
mod.mc_targets=26.1
